version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pointflex-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///instance/pointflex.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend/instance:/app/instance
    networks:
      - pointflex-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - pointflex-network

networks:
  pointflex-network:
    driver: bridge

volumes:
  db_data:
